# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build PunjabiLauncher with Gradle
      run: ./gradlew assembleDebug

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Debug-APP
        path: ./*.apk
